[keybindings.Labyrinth]
"<q>" = "Quit" # Quit the application
"<Ctrl-d>" = "Quit" # Another way to quit
"<Ctrl-c>" = "Quit" # Yet another way to quit
"<Ctrl-z>" = "Suspend" # Suspend the application
"<l>" = "GoRight"
"<h>" = "GoLeft"
"<j>" = "GoDown"
"<k>" = "GoUp"
"<d>" = "GoRight"
"<a>" = "GoLeft"
"<s>" = "GoDown"
"<w>" = "GoUp"
"<up>" = "GoUp"
"<down>" = "GoDown"
"<left>" = "GoLeft"
"<right>" = "GoRight"
"<enter>" = "Confirm"
